export const dataHardcoded = [{
    "Client": "Ericsson",
    "year": "2000",
    "sale": "202",
}, {
    "Client": "Ericsson",
    "year": "2002",
    "sale": "215",
}, {
    "Client": "Ericsson",
    "year": "2004",
    "sale": "179",
}, {
    "Client": "Ericsson",
    "year": "2006",
    "sale": "199",
}, {
    "Client": "Ericsson",
    "year": "2008",
    "sale": "134",
}, {
    "Client": "Ericsson",
    "year": "2010",
    "sale": "176",
}, {
    "Client": "Huawei",
    "year": "2000",
    "sale": "100",
}, {
    "Client": "Huawei",
    "year": "2002",
    "sale": "215",
}, {
    "Client": "Huawei",
    "year": "2004",
    "sale": "179",
}, {
    "Client": "Huawei",
    "year": "2006",
    "sale": "199",
}, {
    "Client": "Huawei",
    "year": "2008",
    "sale": "134",
}, {
    "Client": "Huawei",
    "year": "2013",
    "sale": "176",
}];